os: Visual Studio 2017

build_script:
  # dotnet info
  - ps: dotnet --info 
  - ps: dotnet restore
  - ps: dotnet --verbose build
  - ps: dotnet publish -c release -r win10-x64


test: off 
version: 0.0.1.{build}