os: Visual Studio 2017

build_script:
  - ps: dotnet restore
  - ps: dotnet build
  - ps: dotnet publish -c release -r win10-x64 -o ../../out
  - ps: dotnet msbuild /t:Publish /p:OutputPath=../../dist /p:Configuration=Release /p:RuntimeIdentifiers=win10-x64

artifacts:
  - path: dist
    name: Jira-0.9.0
    type: zip
  - path: out
    name: Jira-0.9.0-old
    type: zip

test: off 
version: 0.9.0.{build}