os: Visual Studio 2017

build_script:
  - ps: dotnet restore
  - ps: dotnet build
  - ps: dotnet publish -c release -r win10-x64 -o ../../windows
  - ps: dotnet publish -c release -r ubuntu.14.04-x64 -o ../../ubuntu
  - ps: dotnet publish -c release -r osx.10.11-x64 -o ../../macosx


artifacts:
  - path: windows
    name: Jira-Win10-x64-0.9.0
    type: zip
  - path: ubuntu
    name: Jira-ubuntu.14.04-x64-0.9.0
    type: zip
  - path: macosx
    name: Jira-osx.10.11-x64-0.9.0
    type: zip

deploy:
  release: jira-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: yYx7QrCyq5Q4NB5FXpdp405AZV9SnuqqOoaN4RiTgK5qPA4eOa7YHTtemhhR4Kk9 # your encrypted token from GitHub
  artifact: /.*\.zip/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only 

test: off 
version: 0.9.0.{build}