os: Visual Studio 2017

build_script:
  - ps: dotnet restore
  - ps: dotnet build
  - ps: dotnet publish -c release -r win10-x64 --output /out

artifacts:
  - path: out
    name: Jira cli
    type: zip

test: off 
version: 0.0.1.{build}