os: Visual Studio 2017

build_script:
  - ps: dotnet restore
  - ps: dotnet build
  - ps: dotnet publish -c release -r win10-x64 -o ../../windows
  - ps: dotnet publish -c release -r ubuntu.14.04-x64 -o ../../ubuntu
  - ps: dotnet publish -c release -r osx.10.11-x64 -o ../../macosx


artifacts:
  - path: windows
    name: Jira-Win10-x64-0.9.0
    type: zip
  - path: ubuntu
    name: Jira-ubuntu.14.04-x64-0.9.0
    type: zip
  - path: macosx
    name: Jira-osx.10.11-x64-0.9.0
    type: zip
  

test: off 
version: 0.9.0.{build}