os: Visual Studio 2017

build_script:
  - ps: dotnet restore
  - ps: dotnet build
  - ps: dotnet msbuild /t:Publish /p:OutputPath=dist /p:Configuration=Release

artifacts:
  - path: C:\projects\jira-cli-dotnet\src\Jira\dist
    name: Jira cli
    type: zip

test: off 
version: 0.0.1.{build}